name: build and publish tweettr

on: [push]

jobs:
  build:
    name: build and publish tweettr
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -e .
    - name: Test with pytest
      run: |
        python setup.py pytest
    - name: Build a binary wheel and a source tarball
      run: |
        python -m pip wheel .
    - name: Publish distribution 📦 to PyPI
      if: startsWith(github.event.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@37e305e7413032d8422456179fee28fac7d25187
      with:
        password: ${{ secrets.pypi_password }}
